MAPR-HIVE-790 Added support for jmxagent at MAPR_JMXREMOTEHOST (#984)
* MAPR-HIVE-790 Added support for jmxagent at MAPR_JMXREMOTEHOST

* MAPR-HIVE-790 Updated jmx properties for the new core

Co-authored-by: avenherak <avenherak@mapr.com>

diff --git a/bin/hive b/bin/hive
--- a/bin/hive
+++ b/bin/hive
@@ -539,6 +539,12 @@ echo "$(date +%F\ %T) WARN [hive] ${HIVE_HOME}/bin/hive: " $* >> "${HIVE_JMX_LOG
 function configureJmx() {
 MAPR_JMX_HIVE_METASTORE_PORT=${MAPR_JMX_HIVE_METASTORE_PORT:-9011}
 MAPR_JMX_HIVE_SERVER2_PORT=${MAPR_JMX_HIVE_SERVER2_PORT:-9012}
+
+isSecure="false"
+if [ -f "${MAPR_HOME}/conf/mapr-clusters.conf" ]; then
+    isSecure=$(head -1 ${MAPR_HOME}/conf/mapr-clusters.conf | grep -o 'secure=\w*' | cut -d= -f2)
+fi
+
 if [ -z "$MAPR_JMXLOCALBINDING" ]; then
   MAPR_JMXLOCALBINDING="false"
 fi
@@ -551,6 +557,14 @@ if [ -z "$MAPR_JMXSSL" ]; then
   MAPR_JMXSSL="false"
 fi
 
+if [ -z "$MAPR_AUTH_LOGIN_CONFIG_FILE" ]; then
+    MAPR_AUTH_LOGIN_CONFIG_FILE="${MAPR_HOME:-/opt/mapr}/conf/mapr.login.conf"
+fi
+
+if [ -z "$MAPR_JMX_LOGIN_CONFIG" ]; then
+  MAPR_JMX_LOGIN_CONFIG="JMX_AGENT_LOGIN"
+fi
+
 if [ -z "$MAPR_JMXDISABLE" ] && [ -z "$MAPR_JMXLOCALHOST" ] && [ -z "$MAPR_JMXREMOTEHOST" ]; then
   logJmxInfo "No MapR JMX options given - defaulting to local binding"
 fi
@@ -558,29 +572,61 @@ fi
 if [ -z "$MAPR_JMXDISABLE" ] || [ "$MAPR_JMXDISABLE" = 'false' ]; then
   # default setting for localBinding
   MAPR_JMX_OPTS="-Dcom.sun.management.jmxremote"
-  if [ "$MAPR_JMXAUTH" = "true" ]; then
-    MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
-    -Dcom.sun.management.jmxremote.password.file=$MAPR_HOME/conf/jmxremote.password \
-    -Dcom.sun.management.jmxremote.access.file=$MAPR_HOME/conf/jmxremote.access"
-  else
-    MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
-  fi
 
   if [ "$MAPR_JMXLOCALHOST" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
     logJmxWarn "Both MAPR_JMXLOCALHOST and MAPR_JMXREMOTEHOST options are enabled - defaulting to MAPR_JMXLOCALHOST config"
     MAPR_JMXREMOTEHOST=false
   fi
+
+  if [ "$isSecure" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+    JMX_JAR=$(echo ${MAPR_HOME:-/opt/mapr}/lib/jmxagent*)
+    if [ -n "$JMX_JAR" ] && [ -f ${JMX_JAR} ]; then
+      MAPR_JMX_OPTS="-javaagent:$JMX_JAR -Dmapr.jmx.agent.login.config=$MAPR_JMX_LOGIN_CONFIG"
+      MAPR_JMXAUTH="true"
+    else
+      echo "jmxagent jar file missed"
+      exit 1
+    fi
+  fi
+
+  if [ "$MAPR_JMXAUTH" = "true" ]; then
+    if [ "$isSecure" = "true" ]; then
+      if [ -f "$MAPR_AUTH_LOGIN_CONFIG_FILE" ] && \
+         [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
+          -Djava.security.auth.login.config=$MAPR_AUTH_LOGIN_CONFIG_FILE \
+          -Dcom.sun.management.jmxremote.access.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access"
+      else
+        echo "JMX login config or access file missing - not starting since we are in secure mode"
+        exit 1
+      fi
+
+      if [ "$MAPR_JMXREMOTEHOST" = "false" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.login.config=$MAPR_JMX_LOGIN_CONFIG"
+      fi
+    else
+      echo "JMX Authentication configured - not starting since we are not in secure mode"
+      exit 1
+    fi
+  else
+      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
+  fi
+
+
+
+
   if [ "$MAPR_JMXLOCALHOST" = "true" ] || [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
-    if [ "$MAPR_JMXSSL" = "true" ]; then
-      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=true"
+    if [ "$MAPR_JMXSSL" = "true" ] && [ "$MAPR_JMXLOCALHOST" = "true" ]; then
+      echo "WARNING: ssl is not supported in localhost. Setting default to false"
+      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
     else
       MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
     fi
 
     if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
       MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Djava.rmi.server.hostname=localhost \
-      -Dcom.sun.management.jmxremote.host=localhost \
-      -Dcom.sun.management.jmxremote.local.only=true"
+        -Dcom.sun.management.jmxremote.host=localhost \
+        -Dcom.sun.management.jmxremote.local.only=true"
     fi
 
     case "$SERVICE" in
@@ -600,19 +646,23 @@ if [ -z "$MAPR_JMXDISABLE" ] || [ "$MAPR_JMXDISABLE" = 'false' ]; then
         MAPR_JMX_OPTS=""
       fi;;
     esac
-
     if [ -z "$MAPR_JMX_OPTS" ]; then
       logJmxWarn "JMX disabled for $SERVICE"
     elif [ -z "$MAPR_JMX_PORT" ]; then
       logJmxWarn "No JMX port given for $SERVICE - disabling TCP base JMX service"
       MAPR_JMX_OPTS=""
     else
-      if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
-        logJmxInfo "Enabling TCP JMX for $SERVICE only on localhost port $MAPR_JMX_PORT"
-      else
+      if [ "$MAPR_JMXREMOTEHOST" = "true" ] && [ "$isSecure" = "true" ]; then
         logJmxInfo "Enabling TCP JMX for $SERVICE on port $MAPR_JMX_PORT"
-      fi
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dmapr.jmx.agent.port=$MAPR_JMX_PORT"
+      else
+        if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
+          logJmxInfo "Enabling TCP JMX for $SERVICE only on localhost port $MAPR_JMX_PORT"
+        else
+          logJmxInfo "Enabling TCP JMX for $SERVICE on port $MAPR_JMX_PORT"
+        fi
         MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.port=$MAPR_JMX_PORT"
+      fi
     fi
   fi
 
